
spring.application.name=tfg

# Puerto del servidor
server.port=8080



# Configuracion de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://mayneyra87:gatosgatos@tfgmay.hcpbb.mongodb.net/tfg?retryWrites=true&w=majority&appName=TFGMay



# crea �ndices autom�ticamente si est�n definidos en las entidades
spring.data.mongodb.auto-index-creation=true

# mostrar logs de las queries si usas un repositorio
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
