
spring.application.name=tfg

# Puerto del servidor
server.port=8081

<<<<<<< HEAD
# Configuracion de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://mayneyra87:gatosgatos@tfgmay.hcpbb.mongodb.net/tfg?retryWrites=true&w=majority&appName=TFGMay

# crea indices automÃ¡ticamente si estan definidos en las entidades
=======
# Configuración de MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://mayneyra87:KVS5wF5SiWkjQodW@tfgmay.hcpbb.mongodb.net/tfg?retryWrites=true&w=majority&appName=TFGMay

# crea índices automáticamente si están definidos en las entidades
>>>>>>> c5d3bdda381c0ba266aed4250b81f58371db7d85
spring.data.mongodb.auto-index-creation=true

# mostrar logs de las queries si usas un repositorio
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
